import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {URL} from 'node:url';
import {LLMRouter} from './src/router.js';
import {TASKMASTER_SYSTEM,AGENTS,buildPlan,assignAgents,readyTasks} from './src/taskmaster.js';
const PORT=process.env.PORT||10000, root=process.cwd();
const router=new LLMRouter();
const memories=new Map();
function json(res,status,data){res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,mcp-session-id','access-control-allow-methods':'GET,POST,OPTIONS'});res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let b='';req.on('data',c=>{b+=c;if(b.length>4e6)req.destroy();});req.on('end',()=>{try{resolve(b?JSON.parse(b):{})}catch(e){reject(e)}});req.on('error',reject)})}
function allowed(u){try{const x=new URL(u);return x.protocol==='https:'||x.protocol==='http:'}catch{return false}}
async function callProvider(p,rq){const base=(p.baseUrl||'').replace(/\/$/,'');if(!base||!p.apiKey||!p.model)throw new Error(`Provider ${p.name||p.id} is not configured`);const r=await fetch(base+'/chat/completions',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${p.apiKey}`},body:JSON.stringify({model:p.model,messages:rq.messages||[{role:'user',content:rq.prompt||''}],temperature:rq.temperature??0.2}),signal:AbortSignal.timeout(rq.timeout||60000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:{message:text}}};if(!r.ok){const e=new Error(data?.error?.message||`Provider HTTP ${r.status}`);e.status=r.status;throw e}return data}
async function proxy(url,options={}){if(!allowed(url))throw new Error('MCP endpoint must be a valid HTTP(S) URL');const r=await fetch(url,{...options,redirect:'manual',signal:AbortSignal.timeout(30000)});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={text}};return {status:r.status,headers:Object.fromEntries(r.headers),data}}
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization,mcp-session-id','access-control-allow-methods':'GET,POST,OPTIONS'});return res.end()}
try{const u=new URL(req.url,'http://localhost');
if(u.pathname==='/health')return json(res,200,{ok:true,service:'cognexa',features:['chat','router','memory','mcp','multi-agent-taskmaster']});
if(u.pathname==='/api/chat'&&req.method==='POST'){const x=await body(req);if(!x.providers?.length&&!x.baseUrl)return json(res,400,{error:'Provide providers or baseUrl'});const providers=x.providers?.length?x.providers:[{id:'selected',name:'Selected',baseUrl:x.baseUrl,apiKey:x.apiKey,model:x.model,priority:100,enabled:true}];router.providers=providers;const selected=providers.find(p=>p.id===x.providerId)||providers[0];const result=await router.chat({provider:selected,task:x.task||{},messages:x.messages,prompt:x.prompt,temperature:x.temperature},callProvider);return json(res,200,{...result,provider:{id:result.provider.id,name:result.provider.name,model:result.provider.model}})}
if(u.pathname==='/api/providers'&&req.method==='POST'){const x=await body(req);router.providers=x.providers||[];return json(res,200,{providers:router.alternatives(null,x.task||{}).map(p=>({id:p.id,name:p.name,model:p.model,priority:p.priority||0}))})}
if(u.pathname==='/api/memory'&&req.method==='GET')return json(res,200,{memories:[...memories.values()]});
if(u.pathname==='/api/memory'&&req.method==='POST'){const x=await body(req);if(!x.text)return json(res,400,{error:'text required'});const item={id:x.id||crypto.randomUUID(),text:x.text,scope:x.scope||'project',tags:x.tags||[],updatedAt:new Date().toISOString()};memories.set(item.id,item);return json(res,201,item)}
if(u.pathname.startsWith('/api/memory/')&&req.method==='DELETE'){memories.delete(u.pathname.split('/').pop());return json(res,200,{ok:true})}
if(u.pathname==='/api/plan'&&req.method==='POST'){const x=await body(req);if(!x.goal)return json(res,400,{error:'goal required'});const providers=x.providers||[];if(!providers.length)return json(res,400,{error:'Connect an LLM first'});router.providers=providers;const r=await router.chat({provider:providers[0],task:{capabilities:['coding']},messages:[{role:'system',content:TASKMASTER_SYSTEM+`\nAgents: ${AGENTS.map(a=>a.name+': '+a.role).join('; ')}\nReturn ONLY valid JSON array.`},{role:'user',content:x.goal}]},callProvider);let raw=r.choices?.[0]?.message?.content||'[]';raw=raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();let tasks;try{tasks=assignAgents(JSON.parse(raw))}catch{tasks=buildPlan([{title:'Review planner output',detail:raw,priority:'high'}])}return json(res,200,{tasks,provider:{id:r.provider.id,name:r.provider.name,model:r.provider.model}})}
if(u.pathname==='/api/task-ready'&&req.method==='POST'){const x=await body(req);return json(res,200,{ready:readyTasks(buildPlan(x.tasks||[]))})}
if(u.pathname==='/api/mcp'&&req.method==='POST'){const x=await body(req);if(!x.url)return json(res,400,{error:'MCP URL is required'});const headers={'content-type':'application/json',accept:'application/json, text/event-stream'};if(x.sessionId)headers['mcp-session-id']=x.sessionId;if(x.authorization)headers.authorization=x.authorization;const out=await proxy(x.url,{method:'POST',headers,body:JSON.stringify(x.request||{})});return json(res,out.status,{status:out.status,headers:out.headers,data:out.data})}
if(u.pathname==='/taskmaster'||u.pathname==='/taskmaster/')return fs.createReadStream(path.join(root,'web','taskmaster.html')).pipe(Object.assign(res,{statusCode:200,headersSent:false}));
let file=u.pathname==='/'?'web/index.html':u.pathname.replace(/^\//,'');if(file.includes('..'))return json(res,400,{error:'bad path'});const p=path.join(root,file);if(fs.existsSync(p)&&fs.statSync(p).isFile()){const ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json'};res.writeHead(200,{'content-type':types[ext]||'text/plain'});return fs.createReadStream(p).pipe(res)}return json(res,404,{error:'not found'});
}catch(e){return json(res,e.status>=400&&e.status<600?e.status:500,{error:e.message})}});server.listen(PORT,'0.0.0.0',()=>console.log(`Cognexa listening on ${PORT}`));