'use client'
import {useEffect,useState} from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

type Message={role:'user'|'assistant'|'system';content:string}
type Chat={id:string;title:string;messages:Message[]}
const KEY='cognexa-chats'
export default function Home(){
 const [chats,setChats]=useState<Chat[]>([]); const [active,setActive]=useState(''); const [input,setInput]=useState(''); const [loading,setLoading]=useState(false); const [system,setSystem]=useState('You are Cognexa, a helpful AI assistant.'); const [showSettings,setShowSettings]=useState(false)
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');setChats(x);if(x[0])setActive(x[0].id)}catch{}},[])
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(chats))},[chats])
 const chat=chats.find(c=>c.id===active)
 function newChat(){const c={id:crypto.randomUUID(),title:'New chat',messages:[]};setChats(x=>[c,...x]);setActive(c.id)}
 async function send(){if(!input.trim()||loading)return; let c=chat;if(!c){newChat();return} const user=input.trim();setInput(''); const messages=[...c.messages,{role:'user' as const,content:user}]; setChats(x=>x.map(q=>q.id===c!.id?{...q,title:q.messages.length?q.title:user.slice(0,40),messages:[...messages,{role:'assistant',content:''}]}:q));setLoading(true)
 try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'system',content:system},...messages]})});if(!r.ok)throw new Error(await r.text());const reader=r.body!.getReader();const dec=new TextDecoder();let text='';while(true){const {done,value}=await reader.read();if(done)break;for(const line of dec.decode(value,{stream:true}).split('\n')){if(!line.startsWith('data: ')||line==='data: [DONE]')continue;try{text+=JSON.parse(line.slice(6)).choices?.[0]?.delta?.content||''}catch{}}setChats(x=>x.map(q=>q.id===c!.id?{...q,messages:q.messages.map((m,i)=>i===q.messages.length-1?{...m,content:text}:m)}:q))}}catch(e){setChats(x=>x.map(q=>q.id===c!.id?{...q,messages:q.messages.map((m,i)=>i===q.messages.length-1?{...m,content:`Error: ${e instanceof Error?e.message:'Request failed'}`}:m)}:q))}finally{setLoading(false)}}
 return <div className="flex h-screen bg-white"><aside className="hidden w-64 flex-col bg-[#f7f7f8] p-3 md:flex"><button onClick={newChat} className="mb-3 rounded-lg border px-3 py-2 text-left hover:bg-white">＋ New chat</button><div className="flex-1 overflow-auto">{chats.map(c=><button key={c.id} onClick={()=>setActive(c.id)} className="mb-1 w-full truncate rounded-lg px-3 py-2 text-left hover:bg-white">{c.title}</button>)}</div><button onClick={()=>setShowSettings(true)} className="rounded-lg px-3 py-2 text-left hover:bg-white">⚙ Settings</button></aside><main className="flex min-w-0 flex-1 flex-col"><header className="flex h-14 items-center justify-between border-b px-4"><button onClick={newChat} className="md:hidden">☰</button><div className="font-semibold">Cognexa <span className="font-normal text-gray-500">· Groq</span></div><button onClick={()=>setShowSettings(true)}>⚙</button></header><section className="chat-scroll flex-1 overflow-auto">{!chat?.messages.length?<div className="mx-auto flex h-full max-w-2xl flex-col items-center justify-center px-5"><h1 className="mb-2 text-3xl font-semibold">How can I help you?</h1><p className="text-gray-500">Ask Cognexa anything.</p></div>:<div className="mx-auto max-w-3xl px-4 py-8">{chat.messages.map((m,i)=><div key={i} className={`mb-8 ${m.role==='user'?'text-right':''}`}><div className={`inline-block max-w-[90%] rounded-2xl px-4 py-3 text-left ${m.role==='user'?'bg-[#f4f4f4]':'bg-white'}`}><ReactMarkdown remarkPlugins={[remarkGfm]}>{m.content||'▌'}</ReactMarkdown></div></div>)}</div>}</section><div className="mx-auto w-full max-w-3xl px-4 pb-5"><div className="flex items-end gap-2 rounded-2xl border p-2 shadow-sm"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Message Cognexa..." className="max-h-40 min-h-12 flex-1 resize-none border-0 p-3 outline-none"/><button onClick={send} disabled={loading||!input.trim()} className="rounded-xl bg-black px-4 py-3 text-white disabled:opacity-30">{loading?'…':'↑'}</button></div><p className="mt-2 text-center text-xs text-gray-400">Cognexa can make mistakes. Check important information.</p></div></main>{showSettings&&<div className="fixed inset-0 flex justify-end bg-black/20"><div className="h-full w-full max-w-md bg-white p-6 shadow-xl"><button onClick={()=>setShowSettings(false)} className="float-right">✕</button><h2 className="mb-6 text-xl font-semibold">Settings</h2><label className="mb-2 block text-sm font-medium">System prompt</label><textarea value={system} onChange={e=>setSystem(e.target.value)} className="h-40 w-full rounded-xl border p-3 outline-none"/><p className="mt-2 text-sm text-gray-500">Model: {process.env.NEXT_PUBLIC_AI_MODEL||'llama-3.3-70b-versatile'}</p></div></div>}</div>
}
